### ISSUE TITLE
how to evaluate the segmentations

### ISSUE THREAD

**Issue by dudu114** [cvdlab/nn-segmentation-for-lar#10]
I have obtained the segmentation results,I will evaluate the results,but i don't have the ground truth of testing dataset.I find that many people evaluate on the online platform,but i need convert the .png to .mha. ITK can perform file type conversion,however ,I need to install the VS,I don't know why i can't install VS successfully.So is there any other method can convert the .png to .mha? I'm in a hurry and I hope someone can help me.Thanks

**Comment by Cesarec88** [comment]
I don't know if it is possible, but I personally don't know how much is useful, because conversion png to mha would mean loss of informations in image. One is a format made to live and transmit image informations in the web(png) . In the other hand .mha it has been made on purpose to keep an higher level of detail for medical analysis. If you have to make this kind of conversion convert all with the last useful universal format that is .nii that is capable also to accept .mha.

**Comment by dudu114** [comment]
If you don't use an online evaluation platform, how do you evaluate the segmentations? Do you have ground truth for evaluation?If you have, could you please provide it to me?Thanks @Cesarec88

**Comment by Cesarec88** [comment]
If you are referring to this repository, the answer is yes we used the Dataset gave from Brats contest few years ago.  I can't pass you the Dataset becuase it's a private repository, but you can directly ask partecipating to the challenge
[link](https://www.med.upenn.edu/sbia/brats2018.html)
